str = "Estudando Python com Madrinha"
str2 = "   Estudando Python  "
tamanho = len(str)
contar = str.count("o")
contar2 = str.count("o",0,15)
fatiamento = str[2:15:2]
achando = str.find("Madrinha")
trocando = str.replace("Python", "Lua")
crescendo = str.upper()
diminuindo = str.lower()
captalize = str.capitalize()
title = str.title()
strip = str2.strip()
stripr = str2.rstrip()
stripl = str2.lstrip()
split = str.split()
join = "-".join(split)
split_join = str.split("-".join(str))

#print(tamanho)
print(contar)
print(contar2)
#print(fatiamento)
print(achando)
#print("Madrinha" in str)
#print(trocando)
#print(crescendo)
#print(diminuindo)
#print(captalize)
#print(title)
#print(str2)
#print(strip)
#print(stripr)
#print(stripl)
#print(split)
#print(join)
#print(split_join)

# terminamos a aula Curso Python #09 - Manipulando Texto